apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-custom
provisioner: file.csi.azure.com
parameters:
  protocol: smb
  skuName: Standard_LRS
mountOptions:
  - mfsymlinks
  - actimeo=30
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
