name: Clone Java17 WKO AKS Sample Auto Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      minutes_time_out:
        description: 'Minutes Time Out'
        required: false
        default: '60'

jobs:
  build:
    name : build-${{ github.event.inputs.workflow_name }}
    # docker is pre-installed on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: 'Set up archived Oracle JDK 8'
        uses: oracle-actions/setup-java@v1
        with:
          uri: https://download.oracle.com/otn-pub/java/jdk/8u391-b13/b291ca3e0c8548b5a51d5a5f50063037/jdk-8u391-linux-aarch64.tar.gz

      - name: Setup tmate session for github debugging
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 180
        with:
          detached: true


